on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pip and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Set-up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          check-latest: true
      - run: npm install
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Deploy CDK
        run: |
          cdk deploy cdk-vpc cdk-ec2 --require-approval never
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_TARGET_ACCOUNT }}

